# Generated by Django 3.0.4 on 2020-03-23 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('male_name', models.CharField(max_length=25)),
                ('female_name', models.CharField(max_length=25)),
                ('percent_in_love', models.PositiveIntegerField()),
                ('percent_in_married', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
