# Generated by Django 3.0.4 on 2020-03-23 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0002_auto_20200323_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='percent_in_love',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='percent_in_married',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
