# Generated by Django 3.0.4 on 2020-03-30 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0005_femalename_malename'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationship',
            name='header',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
